spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    username: zjh
    password: abc123
    url: jdbc:postgresql://${postgres_host}:5432/ecom
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  servlet:
    context-path: /ecom
  port: 8080
logging:
  file:
    name: /home/zjh/logs/ecom.log
