spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      employee: ECOM-EMPLOYEE
      customer: ECOM-CUSTOMER

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: customer-client